### ISSUE TITLE
How to exit interactive in container

### ISSUE THREAD

**Issue by nvcken** [nsourov/Puppeteer-with-xvfb#2]
I want to container in background, I try run
`docker run --network=host scraper`
 then I got stuck cursor in shell after
```
> node index.js

Example app listening on port 3001!
```
What I was wrong, pls correct me

**Comment by entrptaher** [comment]
You want to exit the container without stopping it, right?

If you want a container that run in detached mode all the time, I suggest you use,
```
docker run -d --network=host scraper
```
